pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    ECR_REPO = "717562719168.dkr.ecr.ap-south-1.amazonaws.com/kubeforge-app"
    IMAGE_TAG = "${BUILD_NUMBER}"
    APP_NAME = "kubeforge"
  }

  stages {

    stage("Checkout") {
      steps {
        checkout scm
      }
    }

    stage("Build Image") {
      steps {
        bat "docker build -t ${APP_NAME}:${IMAGE_TAG} ./app"
      }
    }

    stage("Login to ECR") {
      steps {
        bat """
        aws ecr get-login-password --region ${AWS_REGION} |
        docker login --username AWS --password-stdin ${ECR_REPO}
        """
      }
    }

    stage("P  bat Image") {
      steps {
        bat """
        docker tag ${APP_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}
        docker p  bat ${ECR_REPO}:${IMAGE_TAG}
        """
      }
    }

    stage("Deploy GREEN") {
      steps {
        bat """
        sed -i 's/IMAGE_TAG/${IMAGE_TAG}/g' k8s/green/deployment.yaml
        kubectl apply -f k8s/green/
        """
      }
    }

    stage("Wait for GREEN Health") {
      steps {
        bat "kubectl rollout status deployment/kubeforge-green --timeout=180s"
      }
    }

    stage("Switch Traffic to GREEN") {
      steps {
        bat """
        kubectl patch service kubeforge-service \
        -p '{"spec":{"selector":{"app":"kubeforge","version":"green"}}}'
        """
      }
    }
  }

  post {
    success {
      echo "✅ GREEN deployment live with healthy pods"
    }

    failure {
      echo "❌ Deployment failed — rolling back to BLUE"

      bat """
      kubectl patch service kubeforge-service \
      -p '{"spec":{"selector":{"app":"kubeforge","version":"blue"}}}'
      """
    }
  }
}
