pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        ECR_REPO = "717562719168.dkr.ecr.ap-south-1.amazonaws.com/kubeforge-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage("Checkout Code") {
            steps {
                checkout scm
            }
        }

        stage("Build Docker Image") {
            steps {
                script {
                    docker.build("kubeforge-app:${IMAGE_TAG}", "app")
                }
            }
        }

        stage("Login to AWS ECR") {
            steps {
                script {
                    sh '''
                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS --password-stdin $ECR_REPO
                    '''
                }
            }
        }

        stage("Tag Image") {
            steps {
                script {
                    sh """
                    docker tag kubeforge-app:${IMAGE_TAG} $ECR_REPO:${IMAGE_TAG}
                    docker tag kubeforge-app:${IMAGE_TAG} $ECR_REPO:latest
                    """
                }
            }
        }

        stage("Push to ECR") {
            steps {
                script {
                    sh """
                    docker push $ECR_REPO:${IMAGE_TAG}
                    docker push $ECR_REPO:latest
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ CI Pipeline completed successfully!"
        }
        failure {
            echo "❌ CI Pipeline failed!"
        }
    }
}